<script lang="ts" setup>
const { $md } = useNuxtApp();

const slug = useRoute().path.split('/').pop()?.replaceAll('_', '/');
if (slug === undefined) {
  throw createError({
    statusCode: 404,
    statusMessage: 'Brief not found',
  });
}

const report = getReportBySlug(slug);

const estimateReadingTime = (article: string): number => {
  // avg reading speed: ~225 words per minute
  const wordCount = article.trim().split(/\s+/).length;
  return Math.ceil(wordCount / 300);
};

// Reading progress bar logic
const readingProgress = ref(0);
let scrollListener: () => void; // Declare variable

onMounted(() => {
  // Define the listener function
  scrollListener = () => {
    const winScroll = document.documentElement.scrollTop;
    const height = document.documentElement.scrollHeight - document.documentElement.clientHeight;
    readingProgress.value = height > 0 ? (winScroll / height) * 100 : 0; // Avoid division by zero
  };
  window.addEventListener('scroll', scrollListener); // Add using reference
});

onUnmounted(() => {
  if (scrollListener) {
    // Check if listener was defined
    window.removeEventListener('scroll', scrollListener); // Remove using same reference
  }
});

useSeoMeta({
  title: `${report.value.title.toLowerCase()} | meridian`,
  description: `brief for ${report.value.date?.month.toLowerCase()} ${report.value.date?.day}, ${report.value.date?.year}`,
  ogTitle: `${report.value.title.toLowerCase()} | meridian`,
  ogDescription: `brief for ${report.value.date?.month.toLowerCase()} ${report.value.date?.day}, ${report.value.date?.year}`,
});
</script>

<template>
  <div class="fixed top-0 left-0 w-full h-1 z-50">
    <div class="h-full bg-black transition-all duration-150 ease-out" :style="{ width: `${readingProgress}%` }" />
  </div>
  <div>
    <header class="mb-8">
      <h1 class="text-4xl font-bold mb-3">
        {{ report.title.toLowerCase() }}
      </h1>
      <div class="flex text-sm text-gray-600 items-center space-x-2">
        <time>{{ report.date?.month.toLowerCase() }} {{ report.date?.day }}, {{ report.date?.year }}</time>
        <span>•</span>
        <p>{{ estimateReadingTime(report.content) }} min read</p>
      </div>
    </header>

    <article class="prose" v-html="$md.render(report.content)" />

    <div class="mt-16 mb-8">
      <div class="h-px w-full bg-gray-300 mb-8" />
      <div class="flex flex-col text-center gap-8">
        <div class="grid grid-cols-2 gap-y-6 gap-x-12 text-sm">
          <div>
            <p class="text-gray-600 mb-1">total articles</p>
            <p class="font-bold text-base">{{ report.totalArticles || '-' }}</p>
          </div>
          <div>
            <p class="text-gray-600 mb-1">total sources</p>
            <p class="font-bold text-base">{{ report.totalSources || '-' }}</p>
          </div>
          <div>
            <p class="text-gray-600 mb-1">used articles</p>
            <p class="font-bold text-base">{{ report.usedArticles || '-' }}</p>
          </div>
          <div>
            <p class="text-gray-600 mb-1">used sources</p>
            <p class="font-bold text-base">{{ report.usedSources || '-' }}</p>
          </div>
        </div>

        <div class="text-sm">
          <p class="text-gray-600 mb-1">final brief generated by</p>
          <p class="font-bold text-base">{{ report.model_author }}</p>
        </div>
      </div>
    </div>
  </div>
</template>
