name: Sync Upstream

on:
  schedule:
    - cron: '0 0 * * *'  # 每天同步一次（可调整）
  workflow_dispatch:    # 支持手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整历史记录

      - name: Set Git Identity
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"    

      - name: Sync Fork
        run: |
          git remote add upstream https://github.com/iliane5/meridian.git
          git fetch upstream
          git checkout main  # 或你的分支名
          git merge upstream/main
          git push origin
